apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: chorrus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'chorrus-backend'
        static_configs:
          - targets: ['backend-service:80']
        metrics_path: /metrics

      - job_name: 'chorrus-frontend'
        static_configs:
          - targets: ['frontend-service:80']
        metrics_path: /metrics

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true