apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: chorrus
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  REACT_APP_FIREBASE_API_KEY: eW91ci1maXJlYmFzZS1hcGkta2V5
  REACT_APP_FIREBASE_AUTH_DOMAIN: eW91ci1wcm9qZWN0LmZpcmViYXNlYXBwLmNvbQ==
  REACT_APP_FIREBASE_PROJECT_ID: eW91ci1maXJlYmFzZS1wcm9qZWN0LWlk
  REACT_APP_FIREBASE_STORAGE_BUCKET: eW91ci1wcm9qZWN0LmFwcHNwb3QuY29t
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: eW91ci1zZW5kZXItaWQ=
  REACT_APP_FIREBASE_APP_ID: eW91ci1hcHAtaWQ=